version: "3"

services:
    loki:
        image: grafana/loki
        ports:
            - "3100:3100"
            - "9096:9096"
            - "9093:9093"
        volumes:
            # directory must be created first, with uid:gid 10001:10001
            - /opt/docker-home/grafana-loki-prometheus/loki:/loki
            - /opt/docker-home/grafana-loki-prometheus/loki/etc:/etc
        command: -config.file=/etc/loki/local-config.yaml
        restart: always


    promtail:
        depends_on:
            - loki
        image: grafana/promtail
        ports:
            - "9080:9080"
            - "1514:1514"
        volumes:
            # custom config will read logs from the containers of
            # this project
            - /opt/docker-home/grafana-loki-prometheus/loki/promtail/:/etc/promtail/
            # to read container labels and logs
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yaml
        restart: always

    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro


    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - /opt/docker-home/grafana-loki-prometheus/prometheus:/app.cfg
        command: >-
            --config.file=/app.cfg/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles
        restart: always

    grafana:
        depends_on:
            - loki
        image: grafana/grafana
        ports:
            - "30000:3000"
        environment:
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            # directory must be created first, with uid:gid 472:472
            - /opt/docker-home/grafana-loki-prometheus/grafana/lib:/var/lib/grafana
            # automatically configure the loki datasource
            - /opt/docker-home/grafana-loki-prometheus/grafana/etc:/etc/grafana
            # - /opt/docker-home/grafana-loki-prometheus/grafana:/app.cfg
        restart: always

    unpoller:
        image: ghcr.io/unpoller/unpoller:latest
        restart: unless-stopped
        ports:
            - '9130:9130'
        container_name: unpoller
        volumes:
            #- /opt/docker-home/grafana-loki-prometheus/unpoller/etc-unifi-poller:/etc/unifi-poller
            - /opt/docker-home/grafana-loki-prometheus/unpoller/etc-unpoller/up.conf:/etc/unpoller/up.conf
            - /opt/docker-home/grafana-loki-prometheus/unpoller/web:/usr/local/lib/unpoller
        #environment:
            #- UP_INFLUXDB_DISABLE="true"
            #- UP_POLLER_DEBUG="false"
            #- UP_UNIFI_DYNAMIC="false"
            #- UP_UNIFI_CONTROLLER_0_SAVE_ALARMS="true"
            #- UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES="true"
            #- UP_UNIFI_CONTROLLER_0_SAVE_DPI="true"
            #- UP_UNIFI_CONTROLLER_0_SAVE_EVENTS="true"
            #- UP_UNIFI_CONTROLLER_0_SAVE_IDS="true"
            #- UP_UNIFI_CONTROLLER_0_SAVE_SITES="true"
            


