version: "3"

services:
    loki:
        image: grafana/loki
        ports:
            - "3100:3100"
            - "9096:9096"
            - "9093:9093"
        volumes:
            # directory must be created first, with uid:gid 10001:10001
            - /opt/docker-home/grafana-loki-prometheus/loki:/loki
            - /opt/docker-home/grafana-loki-prometheus/loki/etc:/etc
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - grafana-loki
            - promtail-loki
            - world
        restart: always


    promtail:
        depends_on:
            - loki
        image: grafana/promtail
        ports:
            - "9080:9080"
            - "1514:1514"
        volumes:
            # custom config will read logs from the containers of
            # this project
            - /opt/docker-home/grafana-loki-prometheus/loki/promtail/:/etc/promtail/
            # to read container labels and logs
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yaml
        networks:
            - promtail-loki
            - world
        restart: always




    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        networks:
            - prometheus-cadvisor

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - /opt/docker-home/grafana-loki-prometheus/prometheus:/app.cfg
        networks:
            - world
            - prometheus-cadvisor
            - grafana-prometheus
        command: >-
            --config.file=/app.cfg/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles
        restart: always


    grafana:
        depends_on:
            - loki
        image: grafana/grafana
        ports:
            - "30000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            # directory must be created first, with uid:gid 472:472
            - /opt/docker-home/grafana-loki-prometheus/grafana/lib:/var/lib/grafana
            # automatically configure the loki datasource
            - /opt/docker-home/grafana-loki-prometheus/grafana/etc:/etc/grafana
            # - /opt/docker-home/grafana-loki-prometheus/grafana:/app.cfg
        networks:
            - world
            - grafana-loki
            - grafana-prometheus
        restart: always
      

networks:
    world:
    promtail-loki:
        internal: true
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
    prometheus-cadvisor:
        internal: true
